spring:
  security:
    user:
      name: user
      password: 123
      roles:      - USER
  jpa:    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  ssl:
    key-store: D:/Jforce-workspace/test/keystore.jks
    key-store-password: password
    keyAlias: mykey
    key-store-type: JKS
  port: 443
  servlet:
    context-path: /api